### ISSUE TITLE
How to evaluate showSync result?

### ISSUE THREAD

**Issue by WouterBolhuis** [s-h-a-d-o-w/node-native-dialog#1]
I was implementing this is my personal project, but I was wondering whether it was possible to do something with the results of a _showSync_ message. It does not support the .then method or is this something that is not possible.
Basically I want to push a dialogbox that will pause execution, that will pop up over any other application (I couldn't get _show_ to do that) to then take action based on the result of the dialogbox. Can you help me out with that?

**Comment by s-h-a-d-o-w** [comment]
As with Node.js' built-in functions, `showSync` returns the value. See also [its header](https://github.com/s-h-a-d-o-w/node-native-dialog/blob/master/src/win32/index.js#L14).

**Comment by WouterBolhuis** [comment]
Oh you are right, I thought I tried that, thanks!
