### ISSUE TITLE
Can't install node-native-dialog

### ISSUE THREAD

**Issue by mehdirayan** [s-h-a-d-o-w/node-native-dialog#2]
I'm working on windows10  with visual studio community 2019 16.11.25.
The problem is that  winax won't to build.
here is the report:
**npm ERR! code 1
npm ERR! path C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Les projets sont g�n�r�s individuellement dans cette solution. Pour activer la g�n�ration en parall�le, ajoutez le commutateur "-m".
npm ERR!   main.cpp
npm ERR!   utils.cpp
npm ERR! C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\src\utils.cpp(535,14): error C2039: 'auto_ptr' n'est pas membre de 'std' [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj]npm ERR! C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(31): message : voir la d�claration de 'std' [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj]
npm ERR! C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\src\utils.cpp(535,22): error C2065: 'auto_ptr'�: identificateur non d�clar� [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj]
npm ERR! C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\src\utils.cpp(535,23): error C2275: 'DispEnumImpl'�: utilisation non conforme de ce type comme expression [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj]
npm ERR! C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\src\utils.cpp(535,37): error C2065: 'disp'�: identificateur non d�clar� [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj] 
npm ERR! C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\src\utils.cpp(536,51): error C2065: 'disp'�: identificateur non d�clar� [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj] 
npm ERR! C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\src\utils.cpp(539,36): error C2065: 'disp'�: identificateur non d�clar� [C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax\build\node_activex.vcxproj] 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.13.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.1 found at "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python311\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.33214.272) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\Utilisateur\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Utilisateur\\test\\node_modules\\winax\\node_modules\\winax\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',     
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Utilisateur\\AppData\\Local\\node-gyp\\Cache\\18.13.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Utilisateur\\AppData\\Local\\node-gyp\\Cache\\18.13.0',     
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',  
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Utilisateur\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.13.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Utilisateur\\test\\node_modules\\winax\\node_modules\\winax',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Utilisateur\\test\\node_modules\\winax\\node_modules\\winax\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe  
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Utilisateur\test\node_modules\winax\node_modules\winax
npm ERR! gyp ERR! node -v v18.13.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utilisateur\AppData\Local\npm-cache\_logs\2023-01-21T11_44_24_734Z-debug-0.log** 

I make a new project with winax 3.3.4 (node module) and I use the source of node-native-dialog to display the dialog. 
It work perfectly.

**Comment by s-h-a-d-o-w** [comment]
Thanks for making me aware of this!
It also doesn't seem to work on Windows 11 and bumping winax solved it for me as well.

I released it as a new major version because I don't know how backwards-compatible this version of winax is and don't have the time to test that thoroughly.
